server {
    listen 80;
    listen [::]:80;
    server_name kundankrishna.tech www.kundankrishna.tech;

    root /var/www/kundankrishna/html;
    index index.html;

    include snippets/healthhub.conf;

    location / {
        try_files $uri $uri/ =404;
    }
}
